services:
  app:
    image: solarapp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api/
    restart: always
    ports:
      - 5173:80
    container_name: solarapp

  api:
    build:
      context: ./shinemonitor_api
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    container_name: solarapp_api
    volumes:
      - ./shinemonitor_api/token:/app/token
      - ./shinemonitor_api/src/config.py:/app/src/config.py:ro
